name: Bug report
description: Reporte um problema
labels: ["bug"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Explique o bug
    validations:
      required: true
  - type: textarea
    id: passos
    attributes:
      label: Passos para reproduzir
      placeholder: "1. ..."
  - type: input
    id: versao
    attributes:
      label: Versão/Commit
